window.OverworldMaps.Room7 = {
  id: "Room7",
  lowerSrc: "images/maps/room7Lower.png",
  upperSrc: "images/maps/room7Upper.png",
  gameObjects: {
        placeholder: new Person({
            isPlayerControlled: false,
            src: "images/maps/blank.png",
            x: utils.withGrid(4),
            y: utils.withGrid(8),
            walkable: true,
        }),
      hero: new Person({
          isPlayerControlled: true, 
          useShadow: true,
          direction: "up",
          x: utils.withGrid(4),
          y: utils.withGrid(12),
      }),
      boss: new Person({
        isPlayerControlled: false,
        useShadow: true,
        src: "images/characters/people/boss.png",
        x: utils.withGrid(4),
        y: utils.withGrid(7 ),
    }),
  },
  walls: {
    [utils.asGridCoord(4, 13)]: true,
    [utils.asGridCoord(5, 13)]: true,
    [utils.asGridCoord(1, 12)]: true,
    [utils.asGridCoord(2, 12)]: true,
    [utils.asGridCoord(3, 12)]: true,
    [utils.asGridCoord(6, 12)]: true,
    [utils.asGridCoord(7, 12)]: true,
    [utils.asGridCoord(8, 12)]: true,
    [utils.asGridCoord(0, 3)]: true,
    [utils.asGridCoord(0, 4)]: true,
    [utils.asGridCoord(0, 5)]: true,
    [utils.asGridCoord(0, 6)]: true,
    [utils.asGridCoord(0, 7)]: true,
    [utils.asGridCoord(0, 8)]: true,
    [utils.asGridCoord(0, 9)]: true,
    [utils.asGridCoord(0, 10)]: true,
    [utils.asGridCoord(0, 11)]: true,
    [utils.asGridCoord(9, 11)]: true,
    [utils.asGridCoord(9, 10)]: true,
    [utils.asGridCoord(9, 9)]: true,
    [utils.asGridCoord(9, 8)]: true,
    [utils.asGridCoord(9, 7)]: true,
    [utils.asGridCoord(9, 6)]: true,
    [utils.asGridCoord(9, 5)]: true,
    [utils.asGridCoord(9, 4)]: true,
    [utils.asGridCoord(9, 3)]: true,
    [utils.asGridCoord(1, 2)]: true,
    [utils.asGridCoord(2, 2)]: true,
    [utils.asGridCoord(7, 2)]: true,
    [utils.asGridCoord(8,2)]: true,
  },
  start_func: function(){
    document.querySelector(".pokoj").innerText = "???"
    window.map.startCutscene([
      {type: "textMessage",text: "Czekałem na ciebie..."},
      {type: "walk",who: "hero", direction: "up"},
      {type: "walk",who: "hero", direction: "up"},
      {type: "textMessage",text: "Myślisz że możesz mnie pokonać?"},
  ])
  }
};