window.OverworldMaps.Room2 = {
  id: "Room2",
  lowerSrc: "images/maps/room2Lower.png",
  upperSrc: "images/maps/room2Upper.png",
  gameObjects: {
        placeholder: new Person({
            isPlayerControlled: false,
            src: "images/maps/blank.png",
            x: utils.withGrid(4),
            y: utils.withGrid(7),
            walkable: true,
        }),
        Klucz_2: new Person({
            id: "Klucz Labiryntu",
            x: utils.withGrid(46),
            y: utils.withGrid(14),
            pickUp: true,
            counter: 0,
            movePixels: true,
            walkable: true,
            src: "images/Objects/klucz_szafka.png",
            talking: [
                {
                    events: [
                        {who: "Klucz_2",type: "textMessage",text: 'Znalazłeś "Klucz Labiryntu"!'},
                        {who: "Klucz_2",type: "stand",direction: "left",time: 200},
                   ]
               }
           ],
        }),
      hero: new Person({
          isPlayerControlled: true, 
          useShadow: true,
          direction: "up",
          x: utils.withGrid(23),
          y: utils.withGrid(21),
      }),
    drzwi1: new Person({
      id: "drzwi1",
      x: utils.withGrid(2),
      y: utils.withGrid(3),
      counter: 0,
      src: "images/maps/blank.png",
      talking: [
          {
              events: [
                  {type: "do_code", code: 'if(window.heroInventory.find(x => x.id == "Klucz Labiryntu")){const eventHandler = new OverworldEvent({type: "changeMap",map: "Room3",x: utils.withGrid(4),y: utils.withGrid(8),direction: "up"},);eventHandler.init();const eventHandler2 = new OverworldEvent({type: "play_audio",audio:"door_open",volume:"0.1"},);eventHandler2.init();const eventHandler3 = new OverworldEvent({type: "play_audio",audio:"win",volume:"0.1"},);eventHandler3.init();}else{const eventHandler = new OverworldEvent({type: "textMessage",text:"Potrzebujesz klucza nr 2!"},);eventHandler.init();}'}
             ]
         }
     ],
  }),
  drzwi2: new Person({
    id: "drzwi2",
    x: utils.withGrid(3),
    y: utils.withGrid(3),
    counter: 0,
    src: "images/maps/blank.png",
    talking: [
        {
            events: [
                {type: "do_code", code: 'if(window.heroInventory.find(x => x.id == "Klucz Labiryntu")){const eventHandler = new OverworldEvent({type: "changeMap",map: "Room3",x: utils.withGrid(5),y: utils.withGrid(8),direction: "up"},);eventHandler.init();const eventHandler2 = new OverworldEvent({type: "play_audio",audio:"door_open",volume:"0.1"},);eventHandler2.init();const eventHandler3 = new OverworldEvent({type: "play_audio",audio:"win",volume:"0.1"},);eventHandler3.init();}else{const eventHandler = new OverworldEvent({type: "textMessage",text:"Potrzebujesz klucza nr 2!"},);eventHandler.init();}'}
           ]
       }
   ],
}),
  },
  cutsceneSpaces: {
          
  },
  walls: {
    [utils.asGridCoord(1, 4)]: true,
    [utils.asGridCoord(0, 5)]: true,
    [utils.asGridCoord(0, 6)]: true,
    [utils.asGridCoord(0, 7)]: true,
    [utils.asGridCoord(0, 8)]: true,
    [utils.asGridCoord(0, 9)]: true,
    [utils.asGridCoord(4, 4)]: true,
    [utils.asGridCoord(5, 4)]: true,
    [utils.asGridCoord(6, 4)]: true,
    [utils.asGridCoord(7, 4)]: true,
    [utils.asGridCoord(8, 4)]: true,
    [utils.asGridCoord(9, 4)]: true,
    [utils.asGridCoord(10, 4)]: true,
    [utils.asGridCoord(11, 4)]: true,
    [utils.asGridCoord(12, 4)]: true,
    [utils.asGridCoord(13, 4)]: true,
    [utils.asGridCoord(14, 4)]: true,
    [utils.asGridCoord(15, 4)]: true,
    [utils.asGridCoord(16, 4)]: true,
    [utils.asGridCoord(18, 4)]: true,
    [utils.asGridCoord(19, 4)]: true,
    [utils.asGridCoord(20, 4)]: true,
    [utils.asGridCoord(21, 4)]: true,
    [utils.asGridCoord(22, 4)]: true,
    [utils.asGridCoord(23, 4)]: true,
    [utils.asGridCoord(25, 4)]: true,
    [utils.asGridCoord(26, 4)]: true,
    [utils.asGridCoord(27, 4)]: true,
    [utils.asGridCoord(28, 4)]: true,
    [utils.asGridCoord(29, 4)]: true,
    [utils.asGridCoord(30, 4)]: true,
    [utils.asGridCoord(32, 4)]: true,
    [utils.asGridCoord(33, 4)]: true,
    [utils.asGridCoord(34, 4)]: true,
    [utils.asGridCoord(35, 4)]: true,
    [utils.asGridCoord(36, 4)]: true,
    [utils.asGridCoord(37, 4)]: true,
    [utils.asGridCoord(38, 4)]: true,
    [utils.asGridCoord(39, 4)]: true,
    [utils.asGridCoord(40, 4)]: true,
    [utils.asGridCoord(41, 4)]: true,
    [utils.asGridCoord(42, 4)]: true,
    [utils.asGridCoord(43, 4)]: true,
    [utils.asGridCoord(44, 4)]: true,
    [utils.asGridCoord(45, 4)]: true,
    [utils.asGridCoord(46, 4)]: true,
    [utils.asGridCoord(47, 4)]: true,
    [utils.asGridCoord(48, 5)]: true,
    [utils.asGridCoord(48, 6)]: true,
    [utils.asGridCoord(48, 7)]: true,
    [utils.asGridCoord(48, 8)]: true,
    [utils.asGridCoord(48, 9)]: true,
    [utils.asGridCoord(48, 12)]: true,
    [utils.asGridCoord(48, 13)]: true,
    [utils.asGridCoord(48, 14)]: true,
    [utils.asGridCoord(48, 15)]: true,
    [utils.asGridCoord(48, 16)]: true,
    [utils.asGridCoord(48, 17)]: true,
    [utils.asGridCoord(48, 18)]: true,
    [utils.asGridCoord(48, 19)]: true,
    [utils.asGridCoord(48, 20)]: true,
    [utils.asGridCoord(47, 21)]: true,
    [utils.asGridCoord(42, 21)]: true,
    [utils.asGridCoord(43, 21)]: true,
    [utils.asGridCoord(44, 21)]: true,
    [utils.asGridCoord(45, 21)]: true,
    [utils.asGridCoord(29, 21)]: true,
    [utils.asGridCoord(30, 21)]: true,
    [utils.asGridCoord(31, 21)]: true,
    [utils.asGridCoord(32, 21)]: true,
    [utils.asGridCoord(33, 21)]: true,
    [utils.asGridCoord(34, 21)]: true,
    [utils.asGridCoord(35, 21)]: true,
    [utils.asGridCoord(36, 21)]: true,
    [utils.asGridCoord(37, 21)]: true,
    [utils.asGridCoord(38, 21)]: true,
    [utils.asGridCoord(39, 21)]: true,
    [utils.asGridCoord(40, 21)]: true,
    [utils.asGridCoord(25, 21)]: true,
    [utils.asGridCoord(26, 21)]: true,
    [utils.asGridCoord(27, 21)]: true,
    [utils.asGridCoord(24, 22)]: true,
    [utils.asGridCoord(23, 22)]: true,
    [utils.asGridCoord(22, 21)]: true,
    [utils.asGridCoord(21, 21)]: true,
    [utils.asGridCoord(21, 20)]: true,
    [utils.asGridCoord(1, 21)]: true,
    [utils.asGridCoord(3, 21)]: true,
    [utils.asGridCoord(4, 21)]: true,
    [utils.asGridCoord(5, 21)]: true,
    [utils.asGridCoord(6, 21)]: true,
    [utils.asGridCoord(8, 21)]: true,
    [utils.asGridCoord(9, 21)]: true,
    [utils.asGridCoord(10, 21)]: true,
    [utils.asGridCoord(11, 21)]: true,
    [utils.asGridCoord(12, 21)]: true,
    [utils.asGridCoord(13, 21)]: true,
    [utils.asGridCoord(14, 21)]: true,
    [utils.asGridCoord(15, 21)]: true,
    [utils.asGridCoord(16, 21)]: true,
    [utils.asGridCoord(17, 21)]: true,
    [utils.asGridCoord(18, 21)]: true,
    [utils.asGridCoord(19, 21)]: true,
    [utils.asGridCoord(0, 12)]: true,
    [utils.asGridCoord(0, 13)]: true,
    [utils.asGridCoord(0, 14)]: true,
    [utils.asGridCoord(0, 15)]: true,
    [utils.asGridCoord(0, 16)]: true,
    [utils.asGridCoord(0, 17)]: true,
    [utils.asGridCoord(0, 18)]: true,
    [utils.asGridCoord(0, 19)]: true,
    [utils.asGridCoord(0, 20)]: true,
    [utils.asGridCoord(24, 5)]: true,
    [utils.asGridCoord(24, 6)]: true,
    [utils.asGridCoord(24, 7)]: true,
    [utils.asGridCoord(24, 8)]: true,
    [utils.asGridCoord(24, 9)]: true,
    [utils.asGridCoord(24, 10)]: true,
    [utils.asGridCoord(24, 11)]: true,
    [utils.asGridCoord(24, 12)]: true,
    [utils.asGridCoord(24, 13)]: true,
    [utils.asGridCoord(24, 14)]: true,
    [utils.asGridCoord(24, 15)]: true,
    [utils.asGridCoord(24, 16)]: true,
    [utils.asGridCoord(24, 17)]: true,
    [utils.asGridCoord(24, 18)]: true,
    [utils.asGridCoord(20, 18)]: true,
    [utils.asGridCoord(21, 18)]: true,
    [utils.asGridCoord(22, 18)]: true,
    [utils.asGridCoord(20, 19)]: true,
    [utils.asGridCoord(19, 19)]: true,
    [utils.asGridCoord(20, 20)]: true,
    [utils.asGridCoord(20, 16)]: true,
    [utils.asGridCoord(22, 17)]: true,
    [utils.asGridCoord(21, 15)]: true,
    [utils.asGridCoord(22, 15)]: true,
    [utils.asGridCoord(23, 15)]: true,
    [utils.asGridCoord(16, 19)]: true,
    [utils.asGridCoord(17, 19)]: true,
    [utils.asGridCoord(17, 18)]: true,
    [utils.asGridCoord(18, 15)]: true,
    [utils.asGridCoord(18, 16)]: true,
    [utils.asGridCoord(18, 17)]: true,
    [utils.asGridCoord(19, 14)]: true,
    [utils.asGridCoord(20, 13)]: true,
    [utils.asGridCoord(21, 13)]: true,
    [utils.asGridCoord(22, 13)]: true,
    [utils.asGridCoord(23, 11)]: true,
    [utils.asGridCoord(21, 11)]: true,
    [utils.asGridCoord(21, 10)]: true,
    [utils.asGridCoord(21, 9)]: true,
    [utils.asGridCoord(21, 8)]: true,
    [utils.asGridCoord(22, 10)]: true,
    [utils.asGridCoord(22, 7)]: true,
    [utils.asGridCoord(19, 6)]: true,
    [utils.asGridCoord(20, 6)]: true,
    [utils.asGridCoord(21, 6)]: true,
    [utils.asGridCoord(18, 9)]: true,
    [utils.asGridCoord(19, 9)]: true,
    [utils.asGridCoord(19, 8)]: true,
    [utils.asGridCoord(16, 7)]: true,
    [utils.asGridCoord(16, 8)]: true,
    [utils.asGridCoord(16, 9)]: true,
    [utils.asGridCoord(17, 5)]: true,
    [utils.asGridCoord(17, 6)]: true,
    [utils.asGridCoord(17, 7)]: true,
    [utils.asGridCoord(16, 11)]: true,
    [utils.asGridCoord(16, 12)]: true,
    [utils.asGridCoord(19, 11)]: true,
    [utils.asGridCoord(17, 13)]: true,
    [utils.asGridCoord(18, 13)]: true,
    [utils.asGridCoord(18, 12)]: true,
    [utils.asGridCoord(16, 14)]: true,
    [utils.asGridCoord(15, 15)]: true,
    [utils.asGridCoord(16, 16)]: true,
    [utils.asGridCoord(15, 17)]: true,
    [utils.asGridCoord(14, 18)]: true,
    [utils.asGridCoord(14, 19)]: true,
    [utils.asGridCoord(13, 19)]: true,
    [utils.asGridCoord(12, 19)]: true,
    [utils.asGridCoord(11, 16)]: true,
    [utils.asGridCoord(12, 16)]: true,
    [utils.asGridCoord(12, 17)]: true,
    [utils.asGridCoord(11, 17)]: true,
    [utils.asGridCoord(11, 18)]: true,
    [utils.asGridCoord(13, 14)]: true,
    [utils.asGridCoord(13, 15)]: true,
    [utils.asGridCoord(13, 16)]: true,
    [utils.asGridCoord(14, 13)]: true,
    [utils.asGridCoord(14, 12)]: true,
    [utils.asGridCoord(7, 20)]: true,
    [utils.asGridCoord(4, 19)]: true,
    [utils.asGridCoord(5, 19)]: true,
    [utils.asGridCoord(6, 19)]: true,
    [utils.asGridCoord(7, 19)]: true,
    [utils.asGridCoord(8, 19)]: true,
    [utils.asGridCoord(9, 19)]: true,
    [utils.asGridCoord(2, 19)]: true,
    [utils.asGridCoord(2, 20)]: true,
    [utils.asGridCoord(11, 9)]: true,
    [utils.asGridCoord(1, 11)]: true,
    [utils.asGridCoord(1, 10)]: true,
    [utils.asGridCoord(2, 10)]: true,
    [utils.asGridCoord(3, 9)]: true,
    [utils.asGridCoord(4, 9)]: true,
    [utils.asGridCoord(5, 9)]: true,
    [utils.asGridCoord(3, 8)]: true,
    [utils.asGridCoord(4, 7)]: true,
    [utils.asGridCoord(5, 7)]: true,
    [utils.asGridCoord(6, 6)]: true,
    [utils.asGridCoord(7, 7)]: true,
    [utils.asGridCoord(8, 7)]: true,
    [utils.asGridCoord(9, 7)]: true,
    [utils.asGridCoord(11, 7)]: true,
    [utils.asGridCoord(10, 6)]: true,
    [utils.asGridCoord(12, 6)]: true,
    [utils.asGridCoord(13, 6)]: true,
    [utils.asGridCoord(14, 6)]: true,
    [utils.asGridCoord(14, 7)]: true,
    [utils.asGridCoord(14, 8)]: true,
    [utils.asGridCoord(7, 9)]: true,
    [utils.asGridCoord(8, 9)]: true,
    [utils.asGridCoord(9, 9)]: true,
    [utils.asGridCoord(14, 10)]: true,
    [utils.asGridCoord(13, 10)]: true,
    [utils.asGridCoord(12, 11)]: true,
    [utils.asGridCoord(11, 11)]: true,
    [utils.asGridCoord(10, 11)]: true,
    [utils.asGridCoord(9, 12)]: true,
    [utils.asGridCoord(8, 11)]: true,
    [utils.asGridCoord(7, 11)]: true,
    [utils.asGridCoord(6, 11)]: true,
    [utils.asGridCoord(6, 10)]: true,
    [utils.asGridCoord(5, 12)]: true,
    [utils.asGridCoord(4, 11)]: true,
    [utils.asGridCoord(3, 12)]: true,
    [utils.asGridCoord(2, 13)]: true,
    [utils.asGridCoord(3, 14)]: true,
    [utils.asGridCoord(4, 14)]: true,
    [utils.asGridCoord(6, 15)]: true,
    [utils.asGridCoord(7, 15)]: true,
    [utils.asGridCoord(7, 14)]: true,
    [utils.asGridCoord(7, 13)]: true,
    [utils.asGridCoord(2, 15)]: true,
    [utils.asGridCoord(2, 16)]: true,
    [utils.asGridCoord(3, 17)]: true,
    [utils.asGridCoord(4, 17)]: true,
    [utils.asGridCoord(5, 17)]: true,
    [utils.asGridCoord(6, 17)]: true,
    [utils.asGridCoord(7, 17)]: true,
    [utils.asGridCoord(8, 17)]: true,
    [utils.asGridCoord(9, 17)]: true,
    [utils.asGridCoord(9, 16)]: true,
    [utils.asGridCoord(9, 15)]: true,
    [utils.asGridCoord(9, 14)]: true,
    [utils.asGridCoord(10, 14)]: true,
    [utils.asGridCoord(11, 14)]: true,
    [utils.asGridCoord(11, 13)]: true,
    [utils.asGridCoord(25, 11)]: true,
    [utils.asGridCoord(25, 15)]: true,
    [utils.asGridCoord(26, 7)]: true,
    [utils.asGridCoord(26, 10)]: true,
    [utils.asGridCoord(26, 13)]: true,
    [utils.asGridCoord(26, 15)]: true,
    [utils.asGridCoord(26, 17)]: true,
    [utils.asGridCoord(26, 18)]: true,
    [utils.asGridCoord(27, 6)]: true,
    [utils.asGridCoord(27, 8)]: true,
    [utils.asGridCoord(27, 9)]: true,
    [utils.asGridCoord(27, 10)]: true,
    [utils.asGridCoord(27, 11)]: true,
    [utils.asGridCoord(27, 13)]: true,
    [utils.asGridCoord(27, 15)]: true,
    [utils.asGridCoord(27, 18)]: true,
    [utils.asGridCoord(28, 6)]: true,
    [utils.asGridCoord(28, 13)]: true,
    [utils.asGridCoord(28, 16)]: true,
    [utils.asGridCoord(28, 18)]: true,
    [utils.asGridCoord(28, 19)]: true,
    [utils.asGridCoord(28, 20)]: true,
    [utils.asGridCoord(29, 6)]: true,
    [utils.asGridCoord(29, 8)]: true,
    [utils.asGridCoord(29, 9)]: true,
    [utils.asGridCoord(29, 11)]: true,
    [utils.asGridCoord(29, 14)]: true,
    [utils.asGridCoord(29, 19)]: true,
    [utils.asGridCoord(30, 9)]: true,
    [utils.asGridCoord(30, 12)]: true,
    [utils.asGridCoord(30, 13)]: true,
    [utils.asGridCoord(30, 15)]: true,
    [utils.asGridCoord(30, 16)]: true,
    [utils.asGridCoord(30, 17)]: true,
    [utils.asGridCoord(31, 5)]: true,
    [utils.asGridCoord(31, 6)]: true,
    [utils.asGridCoord(31, 7)]: true,
    [utils.asGridCoord(31, 13)]: true,
    [utils.asGridCoord(31, 18)]: true,
    [utils.asGridCoord(31, 19)]: true,
    [utils.asGridCoord(32, 7)]: true,
    [utils.asGridCoord(32, 9)]: true,
    [utils.asGridCoord(32, 11)]: true,
    [utils.asGridCoord(32, 12)]: true,
    [utils.asGridCoord(32, 14)]: true,
    [utils.asGridCoord(32, 16)]: true,
    [utils.asGridCoord(32, 19)]: true,
    [utils.asGridCoord(33, 15)]: true,
    [utils.asGridCoord(33, 17)]: true,
    [utils.asGridCoord(34, 6)]: true,
    [utils.asGridCoord(34, 7)]: true,
    [utils.asGridCoord(34, 8)]: true,
    [utils.asGridCoord(34, 10)]: true,
    [utils.asGridCoord(34, 12)]: true,
    [utils.asGridCoord(34, 13)]: true,
    [utils.asGridCoord(34, 18)]: true,
    [utils.asGridCoord(34, 19)]: true,
    [utils.asGridCoord(35, 10)]: true,
    [utils.asGridCoord(35, 6)]: true,
    [utils.asGridCoord(35, 14)]: true,
    [utils.asGridCoord(35, 15)]: true,
    [utils.asGridCoord(35, 16)]: true,
    [utils.asGridCoord(35, 19)]: true,
    [utils.asGridCoord(36, 6)]: true,
    [utils.asGridCoord(36, 11)]: true,
    [utils.asGridCoord(36, 16)]: true,
    [utils.asGridCoord(36, 17)]: true,
    [utils.asGridCoord(36, 19)]: true,
    [utils.asGridCoord(37, 7)]: true,
    [utils.asGridCoord(37, 9)]: true,
    [utils.asGridCoord(37, 11)]: true,
    [utils.asGridCoord(37, 13)]: true,
    [utils.asGridCoord(37, 14)]: true,
    [utils.asGridCoord(37, 16)]: true,
    [utils.asGridCoord(37, 17)]: true,
    [utils.asGridCoord(37, 18)]: true,
    [utils.asGridCoord(38, 6)]: true,
    [utils.asGridCoord(38, 11)]: true,
    [utils.asGridCoord(38, 14)]: true,
    [utils.asGridCoord(39, 7)]: true,
    [utils.asGridCoord(39, 9)]: true,
    [utils.asGridCoord(39, 12)]: true,
    [utils.asGridCoord(39, 14)]: true,
    [utils.asGridCoord(39, 15)]: true,
    [utils.asGridCoord(39, 16)]: true,
    [utils.asGridCoord(39, 17)]: true,
    [utils.asGridCoord(39, 18)]: true,
    [utils.asGridCoord(39, 19)]: true,
    [utils.asGridCoord(40, 9)]: true,
    [utils.asGridCoord(40, 7)]: true,
    [utils.asGridCoord(40, 11)]: true,
    [utils.asGridCoord(40, 17)]: true,
    [utils.asGridCoord(40, 19)]: true,
    [utils.asGridCoord(41, 7)]: true,
    [utils.asGridCoord(41, 9)]: true,
    [utils.asGridCoord(41, 11)]: true,
    [utils.asGridCoord(41, 14)]: true,
    [utils.asGridCoord(41, 13)]: true,
    [utils.asGridCoord(41, 15)]: true,
    [utils.asGridCoord(41, 19)]: true,
    [utils.asGridCoord(41, 20)]: true,
    [utils.asGridCoord(42, 6)]: true,
    [utils.asGridCoord(42, 10)]: true,
    [utils.asGridCoord(42, 11)]: true,
    [utils.asGridCoord(42, 15)]: true,
    [utils.asGridCoord(42, 17)]: true,
    [utils.asGridCoord(42, 19)]: true,
    [utils.asGridCoord(43, 7)]: true,
    [utils.asGridCoord(43, 9)]: true,
    [utils.asGridCoord(43, 12)]: true,
    [utils.asGridCoord(43, 14)]: true,
    [utils.asGridCoord(43, 17)]: true,
    [utils.asGridCoord(43, 19)]: true,
    [utils.asGridCoord(44, 7)]: true,
    [utils.asGridCoord(44, 9)]: true,
    [utils.asGridCoord(44, 11)]: true,
    [utils.asGridCoord(44, 14)]: true,
    [utils.asGridCoord(44, 17)]: true,
    [utils.asGridCoord(44, 19)]: true,
    [utils.asGridCoord(45, 8)]: true,
    [utils.asGridCoord(45, 9)]: true,
    [utils.asGridCoord(45, 12)]: true,
    [utils.asGridCoord(45, 14)]: true,
    [utils.asGridCoord(45, 17)]: true,
    [utils.asGridCoord(46, 10)]: true,
    [utils.asGridCoord(46, 13)]: true,
    [utils.asGridCoord(46, 15)]: true,
    [utils.asGridCoord(46, 16)]: true,
    [utils.asGridCoord(46, 19)]: true,
    [utils.asGridCoord(46, 20)]: true,
    [utils.asGridCoord(47, 10)]: true,
    [utils.asGridCoord(47, 11)]: true,
  },
  start_func:  () => {
    document.querySelector('canvas').classList.add("room2")
    document.querySelector('.game-container').classList.add("room2")
      const progress = new Progress();
      progress.load();
      progress.heroInventory.forEach(e =>{
          if(e.id == "Klucz Labiryntu"){
              delete window.OverworldMaps.Room2.gameObjects.Klucz_2;
          }
      })
    const quest = new QuestLog({onComplete: () => {}});
    if(window.quests.find(x => x.id == "Zagadka").progress == 0){
        quest.end_quest("Zagadka");
    }
    if(!window.quests.find(x => x.id == "Labirynt")){
        quest.add_quest({id: "Labirynt",desc: "Znajdź wyjście z labiryntu",});
    }
    document.querySelector(".pokoj").innerText = "Komnata wytrwałości"
  }
};